[package]
name = "risingwave_meta"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
anyhow = "1"
arc-swap = "1"
assert_matches = "1"
async-trait = "0.1"
aws-config = { workspace = true }
aws-sdk-ec2 = { workspace = true }
bytes = { version = "1", features = ["serde"] }
clap = { version = "4", features = ["derive", "env"] }
crepe = "0.1"
easy-ext = "1"
either = "1"
enum-as-inner = "0.5"
etcd-client = { version = "0.2", package = "madsim-etcd-client" }
fail = "0.5"
function_name = "0.3.0"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
hex = "0.4"
hyper = "0.14"
itertools = "0.10"
memcomparable = { version = "0.1" }
mime_guess = "2"
num-integer = "0.1"
num-traits = "0.2"
parking_lot = { version = "0.12", features = ["arc_lock"] }
prometheus = "0.13"
prometheus-http-query = "0.6"
prost = "0.11"
rand = "0.8"
reqwest = "0.11"
risingwave_backup = { path = "../storage/backup" }
risingwave_common = { path = "../common" }
risingwave_common_proc_macro = { path = "../common/proc_macro" }
risingwave_common_service = { path = "../common/common_service" }
risingwave_connector = { path = "../connector" }
risingwave_hummock_sdk = { path = "../storage/hummock_sdk" }
risingwave_object_store = { path = "../object_store" }
risingwave_pb = { path = "../prost" }
risingwave_rpc_client = { path = "../rpc_client" }
scopeguard = "1.1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sync-point = { path = "../utils/sync-point" }
thiserror = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tokio-retry = "0.3"
tokio-stream = { version = "0.1", features = ["net"] }
tonic = { version = "0.2", package = "madsim-tonic" }
tower = { version = "0.4", features = ["util", "load-shed"] }
tracing = "0.1"
url = "2"
uuid = { version = "1", features = ["v4"] }

[target.'cfg(not(madsim))'.dependencies]
axum = "0.6"
tower-http = { version = "0.3", features = ["add-extension", "cors", "fs"] }
workspace-hack = { path = "../workspace-hack" }

[dev-dependencies]
assert_matches = "1"
maplit = "1.0.2"
rand = "0.8"
risingwave_test_runner = { path = "../test_runner" }
static_assertions = "1"
tempfile = "3"

[features]
test = []
failpoints = ["fail/failpoints"]
